#schema: https://taskfile.dev/schema.json
version: '3.17'

tasks:
  run:
    desc: Run
    cmds:
      - go run .

  lint:
    desc: Run lint with auto-fix where possible (dev workflow)
    cmds:
      - golangci-lint run --fix
