#schema: https://taskfile.dev/schema.json
version: '3.17'

tasks:
  run:
    desc: Run
    deps:
      - task: build
    cmds:
      - ./bin/dev.js {{.CLI_ARGS}}

  lint:
    desc: Lint
    cmds:
      - npm run lint

  build:
    desc: Build
    cmds:
      - npm run build
    generates:
      - ./bin/**
