// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package validator

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockGit creates a new instance of MockGit. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGit(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGit {
	mock := &MockGit{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGit is an autogenerated mock type for the Git type
type MockGit struct {
	mock.Mock
}

type MockGit_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGit) EXPECT() *MockGit_Expecter {
	return &MockGit_Expecter{mock: &_m.Mock}
}

// FilesChanged provides a mock function for the type MockGit
func (_mock *MockGit) FilesChanged(ctx context.Context, sha string) ([]string, error) {
	ret := _mock.Called(ctx, sha)

	if len(ret) == 0 {
		panic("no return value specified for FilesChanged")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]string, error)); ok {
		return returnFunc(ctx, sha)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []string); ok {
		r0 = returnFunc(ctx, sha)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, sha)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGit_FilesChanged_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FilesChanged'
type MockGit_FilesChanged_Call struct {
	*mock.Call
}

// FilesChanged is a helper method to define mock.On call
//   - ctx context.Context
//   - sha string
func (_e *MockGit_Expecter) FilesChanged(ctx interface{}, sha interface{}) *MockGit_FilesChanged_Call {
	return &MockGit_FilesChanged_Call{Call: _e.mock.On("FilesChanged", ctx, sha)}
}

func (_c *MockGit_FilesChanged_Call) Run(run func(ctx context.Context, sha string)) *MockGit_FilesChanged_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGit_FilesChanged_Call) Return(strings []string, err error) *MockGit_FilesChanged_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockGit_FilesChanged_Call) RunAndReturn(run func(ctx context.Context, sha string) ([]string, error)) *MockGit_FilesChanged_Call {
	_c.Call.Return(run)
	return _c
}

// Message provides a mock function for the type MockGit
func (_mock *MockGit) Message(ctx context.Context, sha string) (string, error) {
	ret := _mock.Called(ctx, sha)

	if len(ret) == 0 {
		panic("no return value specified for Message")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, sha)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, sha)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, sha)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGit_Message_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Message'
type MockGit_Message_Call struct {
	*mock.Call
}

// Message is a helper method to define mock.On call
//   - ctx context.Context
//   - sha string
func (_e *MockGit_Expecter) Message(ctx interface{}, sha interface{}) *MockGit_Message_Call {
	return &MockGit_Message_Call{Call: _e.mock.On("Message", ctx, sha)}
}

func (_c *MockGit_Message_Call) Run(run func(ctx context.Context, sha string)) *MockGit_Message_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGit_Message_Call) Return(s string, err error) *MockGit_Message_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockGit_Message_Call) RunAndReturn(run func(ctx context.Context, sha string) (string, error)) *MockGit_Message_Call {
	_c.Call.Return(run)
	return _c
}

// SHA provides a mock function for the type MockGit
func (_mock *MockGit) SHA(ctx context.Context, from string, to string) ([]string, error) {
	ret := _mock.Called(ctx, from, to)

	if len(ret) == 0 {
		panic("no return value specified for SHA")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) ([]string, error)); ok {
		return returnFunc(ctx, from, to)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) []string); ok {
		r0 = returnFunc(ctx, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, from, to)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGit_SHA_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SHA'
type MockGit_SHA_Call struct {
	*mock.Call
}

// SHA is a helper method to define mock.On call
//   - ctx context.Context
//   - from string
//   - to string
func (_e *MockGit_Expecter) SHA(ctx interface{}, from interface{}, to interface{}) *MockGit_SHA_Call {
	return &MockGit_SHA_Call{Call: _e.mock.On("SHA", ctx, from, to)}
}

func (_c *MockGit_SHA_Call) Run(run func(ctx context.Context, from string, to string)) *MockGit_SHA_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGit_SHA_Call) Return(strings []string, err error) *MockGit_SHA_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockGit_SHA_Call) RunAndReturn(run func(ctx context.Context, from string, to string) ([]string, error)) *MockGit_SHA_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockScopeParser creates a new instance of MockScopeParser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockScopeParser(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockScopeParser {
	mock := &MockScopeParser{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockScopeParser is an autogenerated mock type for the ScopeParser type
type MockScopeParser struct {
	mock.Mock
}

type MockScopeParser_Expecter struct {
	mock *mock.Mock
}

func (_m *MockScopeParser) EXPECT() *MockScopeParser_Expecter {
	return &MockScopeParser_Expecter{mock: &_m.Mock}
}

// Parse provides a mock function for the type MockScopeParser
func (_mock *MockScopeParser) Parse(message string) string {
	ret := _mock.Called(message)

	if len(ret) == 0 {
		panic("no return value specified for Parse")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(message)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockScopeParser_Parse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Parse'
type MockScopeParser_Parse_Call struct {
	*mock.Call
}

// Parse is a helper method to define mock.On call
//   - message string
func (_e *MockScopeParser_Expecter) Parse(message interface{}) *MockScopeParser_Parse_Call {
	return &MockScopeParser_Parse_Call{Call: _e.mock.On("Parse", message)}
}

func (_c *MockScopeParser_Parse_Call) Run(run func(message string)) *MockScopeParser_Parse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockScopeParser_Parse_Call) Return(s string) *MockScopeParser_Parse_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockScopeParser_Parse_Call) RunAndReturn(run func(message string) string) *MockScopeParser_Parse_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOutsiderFinder creates a new instance of MockOutsiderFinder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOutsiderFinder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOutsiderFinder {
	mock := &MockOutsiderFinder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOutsiderFinder is an autogenerated mock type for the OutsiderFinder type
type MockOutsiderFinder struct {
	mock.Mock
}

type MockOutsiderFinder_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOutsiderFinder) EXPECT() *MockOutsiderFinder_Expecter {
	return &MockOutsiderFinder_Expecter{mock: &_m.Mock}
}

// Find provides a mock function for the type MockOutsiderFinder
func (_mock *MockOutsiderFinder) Find(scope string, files []string) []Outsider {
	ret := _mock.Called(scope, files)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 []Outsider
	if returnFunc, ok := ret.Get(0).(func(string, []string) []Outsider); ok {
		r0 = returnFunc(scope, files)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Outsider)
		}
	}
	return r0
}

// MockOutsiderFinder_Find_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Find'
type MockOutsiderFinder_Find_Call struct {
	*mock.Call
}

// Find is a helper method to define mock.On call
//   - scope string
//   - files []string
func (_e *MockOutsiderFinder_Expecter) Find(scope interface{}, files interface{}) *MockOutsiderFinder_Find_Call {
	return &MockOutsiderFinder_Find_Call{Call: _e.mock.On("Find", scope, files)}
}

func (_c *MockOutsiderFinder_Find_Call) Run(run func(scope string, files []string)) *MockOutsiderFinder_Find_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOutsiderFinder_Find_Call) Return(outsiders []Outsider) *MockOutsiderFinder_Find_Call {
	_c.Call.Return(outsiders)
	return _c
}

func (_c *MockOutsiderFinder_Find_Call) RunAndReturn(run func(scope string, files []string) []Outsider) *MockOutsiderFinder_Find_Call {
	_c.Call.Return(run)
	return _c
}
